# Generated by Django 4.2.6 on 2023-10-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyOfficers',
            field=models.ManyToManyField(to='data_sources.companyofficer'),
        ),
    ]
