# Generated by Django 4.2.6 on 2023-10-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0002_alter_company_companyofficers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ebitda',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='netIncomeToCommon',
            field=models.BigIntegerField(null=True),
        ),
    ]
