# Generated by Django 4.2.6 on 2023-10-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0003_alter_company_ebitda_alter_company_netincometocommon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyOfficers',
            field=models.ManyToManyField(null=True, to='data_sources.companyofficer'),
        ),
    ]
